"""Assemble the book PDF from the per-section PDFs.

Ported from the Vacuum book's assembler, without its two-volume split and cover
art. Pipeline:
  1. Read out/manifest.json and the per-section PDFs from render-sections.mjs.
  2. Count pages per section: body pages are numbered 1..N; cover and contents
     are unnumbered.
  3. Merge the body, then locate every Contents heading in it.
  4. Render the cover and the Contents (grouped by Part, with real page
     numbers) via render-html.mjs, and merge cover + contents + body.
  5. Stamp running heads and "n / N" page numbers; link the Contents rows.
  6. Rewrite the body's localhost cross-references into page jumps.
  7. Add the PDF outline (bookmarks).

Run from the repo root after render-sections.mjs:  python pdf-build/assemble.py
"""
import json
import subprocess
import sys
from html import escape
from pathlib import Path

import fitz  # PyMuPDF
from pypdf import PdfReader, PdfWriter

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from headings import contents_subsections, section_headings  # noqa: E402
from links import (  # noqa: E402
    _page_for_heading, build_anchor_map, expected_internal_targets, format_link_summary, resolve_links,
)
from siteconf import BOOK_TITLE  # noqa: E402

OUT = HERE / "out"
DIST_FINAL = HERE / (BOOK_TITLE.replace(" ", "-") + ".pdf")

ACCENT = "#1a5276"
AUTHOR = "Oleksiy V. Penkov"
# Two lines, broken by hand: the balanced break of _two_lines splits "Reflectivity
# Curves".
BOOK_SUB_LINES = ("Fitting X-Ray Reflectivity Curves", "with X-Ray Calc 3")
# The copyright notice and the licence, as the web home page carries them (author, 2026-09-25).
# Two lines: on one, the licence runs into the third Bragg peak of the hero.
COVER_TAG = (f"© 2026 {AUTHOR}", "CC BY 4.0")
BOOK_SUBJECT = " ".join(BOOK_SUB_LINES)

# The cover is a companion to the Vacuum book's: the same skeleton (near-black
# type block, one accent band, a monochrome hero cropped on its edges), with
# X-ray amber in the place of argon violet (author, 2026-09-25). Kept separate
# from ACCENT, which the Contents page uses. The band takes the deeper amber so
# white type on it stays legible; the fit line takes the bright tint, which
# reads on black.
COVER_ACCENT = "#b0681a"
COVER_TINT = "#f0a040"
# The measured points: red (author, 2026-09-25; blue was the other candidate).
COVER_DATA = "#ff5a5a"
HERO_SVG = HERE / "cover-hero.svg"   # generated by cover_hero.py
HERO_MATH = HERE / "cover-math.html"  # generated by cover-math.mjs (run by cover_hero.py)
KATEX_CSS = HERE.parent / "node_modules" / "katex" / "dist" / "katex.min.css"


def node_render(html_path: Path, pdf_path: Path) -> None:
    subprocess.run(["node", str(HERE / "render-html.mjs"), str(html_path), str(pdf_path)], check=True)


def page_count(pdf: Path) -> int:
    return len(PdfReader(str(pdf)).pages)


def _two_lines(text: str) -> str:
    """Balance a short string across two ranged-left lines, breaking on a word
    boundary. Letting the browser wrap puts the break near the measure's edge,
    where a font substitution or a reworded string flips it to one line or
    three. (From the Vacuum book's assembler.)"""
    words = text.split()
    if len(words) < 2:
        return escape(text)
    half = len(text) / 2
    first: list[str] = []
    used = 0
    for word in words:
        if first and used + len(word) > half:
            break
        first.append(word)
        used += len(word) + 1
    if len(first) == len(words):          # never leave the second line empty
        first = words[:-1]
    return escape(" ".join(first)) + "<br>" + escape(" ".join(words[len(first):]))


def cover_html() -> str:
    hero = HERO_SVG.read_text(encoding="utf-8")
    hero = hero.replace("{accent}", COVER_ACCENT).replace("{tint}", COVER_TINT).replace("{data}", COVER_DATA)
    return f"""<!doctype html><html><head><meta charset="utf-8">
<link rel="stylesheet" href="{KATEX_CSS.as_uri()}"><style>
  @page{{size:148mm 210mm;margin:0;}}
  html,body{{margin:0;padding:0;}}
  /* Exactly one page: the assembler feeds page_count(cover.pdf) into every
     page number and outline offset downstream, so the height is fixed and the
     overflow hidden. */
  .page{{position:relative;width:148mm;height:210mm;overflow:hidden;
         background:linear-gradient(160deg,#14181d 0%,#0a0c0f 60%,#08090b 100%);}}
  .type{{position:absolute;top:0;left:0;right:0;height:80mm;
         padding:22mm 14mm 0;box-sizing:border-box;}}
  h1{{margin:0;font-family:'Bodoni MT','Perpetua','Baskerville Old Face',Georgia,serif;
      font-weight:400;font-size:36pt;line-height:1.05;letter-spacing:.12em;
      text-transform:uppercase;color:#f2f4f5;}}
  .sub{{margin:6mm 0 0;font-family:'Cambria','Constantia',Georgia,serif;font-weight:700;
        font-size:14pt;line-height:1.28;color:#fff;}}
  .band{{position:absolute;top:80mm;left:0;right:0;height:10mm;background:{COVER_ACCENT};
         display:flex;align-items:center;padding:0 14mm;box-sizing:border-box;}}
  .who{{font-family:'Cambria','Constantia',Georgia,serif;font-size:13pt;color:#fff;}}
  /* The two formulas float behind the curve as faint ghosts: drawn before the
     hero, so the curve, the note and the vignette all pass over them. */
  .ghost{{position:absolute;color:rgba(235,240,245,.13);white-space:nowrap;}}
  .ghost .katex-display{{margin:0;}}
  .ghost-bragg{{top:143mm;left:52mm;font-size:21pt;transform:rotate(-5deg);}}
  .ghost-parratt{{top:174mm;left:40mm;font-size:17pt;transform:rotate(3deg);}}
  .hero{{position:absolute;top:90mm;left:0;width:148mm;height:120mm;display:block;}}
  /* 8pt, not 7: verify_pdf's MIN_TEXT_PT floor is 7.9 and covers this page too. */
  .mark{{position:absolute;left:14mm;bottom:6mm;font-family:'Cambria',Georgia,serif;
         font-size:8pt;letter-spacing:.14em;color:rgba(255,255,255,.72);}}
</style></head><body><div class="page">
  <div class="type">
    <h1>{_two_lines(BOOK_TITLE)}</h1>
    <div class="sub">{"<br>".join(escape(t) for t in BOOK_SUB_LINES)}</div>
  </div>
  <div class="band"><span class="who">{escape(AUTHOR)}</span></div>
  {HERO_MATH.read_text(encoding="utf-8")}
  {hero}
  <div class="mark">{"<br>".join(escape(t) for t in COVER_TAG)}</div>
</div></body></html>"""


def toc_html(entries, subs) -> str:
    """entries: dicts with number, title, part, partHeading, start_page, slug.
    subs: {slug: [(heading_id, text, body_page)]}, body pages 1-based."""
    rows = []
    last_part = None
    for e in entries:
        if e["part"] != last_part:
            last_part = e["part"]
            rows.append(f'<div class="part">{escape(e["partHeading"])}</div>')
        rows.append(
            '<div class="row">'
            f'<span class="num">{escape(e["number"])}</span>'
            f'<span class="title">{escape(e["title"])}</span>'
            '<span class="dots"></span>'
            f'<span class="pg">{e["start_page"]}</span></div>'
        )
        for _hid, text, page in subs.get(e["slug"], []):
            rows.append(
                '<div class="row row-sub"><span class="num"></span>'
                f'<span class="title">{escape(text)}</span>'
                f'<span class="dots"></span><span class="pg">{page}</span></div>'
            )
    body = "\n".join(rows)
    has_subs = any(subs.get(e["slug"]) for e in entries)
    sub_css = (
        "  .row-sub{font-size:8.5pt;margin:.15em 0;}\n"
        "  .row-sub .title{padding-left:1.6em;color:#3d4d5c;}\n"
        "  .row-sub .pg{color:#7b8794;}\n"
    ) if has_subs else ""
    # The margin lives on @page, not on .page padding: padding is spent once, at
    # the top of the first sheet, and the Vacuum book's second contents sheet
    # began with its first row touching the trim edge. The 14mm top leaves room
    # for the "Contents (continued)" head stamped at 8mm.
    return f"""<!doctype html><html><head><meta charset="utf-8"><style>
  @page{{size:148mm 210mm;margin:14mm 16mm;}}
  html,body{{margin:0;padding:0;font-family:'Segoe UI',system-ui,sans-serif;color:#1a2733;}}
  .row{{break-inside:avoid;display:flex;align-items:baseline;gap:.5em;margin:.35em 0;font-size:10pt;}}
  h1{{font-size:20pt;color:{ACCENT};margin:0 0 .2em;border-bottom:2px solid {ACCENT};padding-bottom:.2em;}}
  .part{{margin:1.1em 0 .4em;font-size:9pt;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:{ACCENT};}}
{sub_css}  .num{{width:2.2em;flex:none;color:{ACCENT};font-weight:700;text-align:right;}}
  .title{{flex:none;}}
  .dots{{flex:1;border-bottom:1px dotted #9bb0c0;transform:translateY(-.25em);margin:0 .4em;}}
  .pg{{flex:none;font-variant-numeric:tabular-nums;color:#52606d;}}
</style></head><body><div class="page">
  <h1>Contents</h1>
  {body}
</div></body></html>"""


# Running heads, "Contents (continued)" and page numbers are stamped with a
# Unicode TrueType font. PyMuPDF's built-in Helvetica has no Greek and no
# ellipsis: Chapter 2's head "2θ or θ: the angle on your screen" printed as
# "2· or ·: …", and every truncated head ended in "·". The pipeline runs on
# Windows (CLAUDE.md), where Segoe UI is always present. Arial, Tahoma, Verdana
# and Calibri map the space and the no-break space to one glyph, so their
# stamped spaces extract as U+00A0 and a text search for a head fails.
RUNHEAD_FONT_FILE = Path("C:/Windows/Fonts/segoeui.ttf")
if not RUNHEAD_FONT_FILE.exists():
    raise SystemExit(f"running-head font not found: {RUNHEAD_FONT_FILE}")
RUNHEAD_FONT = fitz.Font(fontfile=str(RUNHEAD_FONT_FILE))


def stamp_text(page, point, text: str, fontsize: float, color) -> None:
    """Stamp one line in the running-head font (embedded once per page)."""
    page.insert_font(fontname="RH", fontfile=str(RUNHEAD_FONT_FILE))
    page.insert_text(point, text, fontname="RH", fontsize=fontsize, color=color)


def section_label(entry: dict) -> str:
    """Outline entry and running-head label: "Chapter 4: X-Rays Meet a Surface",
    "Appendix A: Notation and Units", or the bare title for the Introduction.
    A colon, never an em-dash (STYLE.md §4.2)."""
    return f'{entry["label"]}: {entry["title"]}' if entry.get("label") else entry["title"]


def fit_running_head(left: str, right: str, avail_pt: float, gap_pt: float,
                     fontname: "str | fitz.Font", fontsize: float) -> str | None:
    """The right-hand running-head string that fits beside `left`, or None.

    The left half (the chapter) is the coarse locator and never gives way; the
    right half (the current section) is truncated on a word boundary with an
    ellipsis. If not even its first word fits, nothing is stamped.
    """
    if not right:
        return None

    def w(s: str) -> float:
        if isinstance(fontname, fitz.Font):
            return fontname.text_length(s, fontsize=fontsize)
        return fitz.get_text_length(s, fontname=fontname, fontsize=fontsize)

    budget = avail_pt - w(left) - gap_pt
    if budget <= 0:
        return None
    if w(right) <= budget:
        return right
    kept: list[str] = []
    for word in right.split(" "):
        if w(" ".join(kept + [word]) + "…") > budget:
            break
        kept.append(word)
    return " ".join(kept) + "…" if kept else None


def resolve_subsections(bodydoc, entries, all_subs, page_for_heading=_page_for_heading):
    """Locate every Contents heading inside the merged body PDF.

    Returns (subs, resolved, total, unresolved); subs is
    {slug: [(heading_id, text, body_page)]} with body_page 1-based. Ties on one
    page are ordered by SOURCE order, never by id or text.
    """
    subs: dict[str, list[tuple[str, str, int]]] = {}
    resolved = total = 0
    unresolved: list[str] = []
    for e in entries:
        first = e["start_page"] - 1
        last = first + e["pages"] - 1
        found = []
        for idx, (hid, text) in enumerate(all_subs.get(e["slug"], [])):
            total += 1
            pg = page_for_heading(bodydoc, text, first, last)
            if pg is None:
                unresolved.append(f"{e['slug']}: {text!r}")
                continue
            found.append((pg, idx, hid, text))
            resolved += 1
        found.sort()
        subs[e["slug"]] = [(hid, text, pg + 1) for pg, _idx, hid, text in found]
    return subs, resolved, total, unresolved


def contents_targets(entries, subs):
    """(search_text, body_page) for every Contents row, in document order."""
    targets = []
    for e in entries:
        targets.append((e["title"], e["start_page"]))
        for _hid, text, page in subs.get(e["slug"], []):
            targets.append((text, page))
    return targets


def toc_mark_page(front_pages: int, body_page: int) -> int:
    """1-based absolute page number for a PDF outline entry."""
    return front_pages + body_page


def link_target_page(front_pages: int, body_page: int) -> int:
    """0-based absolute page index for a GOTO link annotation's target."""
    return front_pages + body_page - 1


def main() -> None:
    # A failed assemble must not leave the previous book looking current:
    # verify_pdf.py defaults to this path.
    DIST_FINAL.unlink(missing_ok=True)

    manifest_path = OUT / "manifest.json"
    if not manifest_path.exists():
        raise SystemExit(f"{manifest_path} not found. Run render-sections.mjs first; "
                         "it writes the manifest only when every section passed.")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    running = 1
    entries = []
    for sec in manifest:
        n = page_count(OUT / sec["file"])
        entries.append({**sec, "pages": n, "start_page": running})
        running += n

    (OUT / "cover.html").write_text(cover_html(), encoding="utf-8")
    node_render(OUT / "cover.html", OUT / "cover.pdf")
    cover_pages = page_count(OUT / "cover.pdf")
    if cover_pages != 1:
        raise SystemExit(f"cover.pdf rendered {cover_pages} pages, expected 1")

    # Body first: a Contents row's page number is only knowable by finding its
    # heading in the merged body. Body numbers are body-relative, so the
    # Contents' own length shifts nothing.
    body_writer = PdfWriter()
    for sec in manifest:
        for p in PdfReader(str(OUT / sec["file"])).pages:
            body_writer.add_page(p)
    body_only = OUT / "_body.pdf"
    with open(body_only, "wb") as fh:
        body_writer.write(fh)

    dist = HERE.parent / "dist"
    if not dist.is_dir():
        raise SystemExit(f"dist/ not found at {dist}; run `npm run build` before assembling")

    all_subs = contents_subsections(dist)
    bodydoc = fitz.open(str(body_only))
    subs, resolved, total, unresolved = resolve_subsections(bodydoc, entries, all_subs)
    bodydoc.close()
    if resolved != total:
        raise SystemExit(
            f"located {resolved} of {total} Contents headings in the body; missing: "
            + "; ".join(unresolved[:5]) + (f" (+{len(unresolved) - 5} more)" if len(unresolved) > 5 else ""))

    (OUT / "toc.html").write_text(toc_html(entries, subs), encoding="utf-8")
    node_render(OUT / "toc.html", OUT / "toc.pdf")
    front_pages = cover_pages + page_count(OUT / "toc.pdf")

    writer = PdfWriter()
    for part in ("cover.pdf", "toc.pdf", "_body.pdf"):
        for p in PdfReader(str(OUT / part)).pages:
            writer.add_page(p)
    merged = OUT / "_merged.pdf"
    with open(merged, "wb") as fh:
        writer.write(fh)

    doc = fitz.open(str(merged))
    toc_marks = [[1, "Cover", 1], [1, "Contents", cover_pages + 1]]
    for e in entries:
        toc_marks.append([1, section_label(e), toc_mark_page(front_pages, e["start_page"])])
        for _hid, text, page in subs.get(e["slug"], []):
            toc_marks.append([2, text, toc_mark_page(front_pages, page)])

    accent_rgb = (0x1A / 255, 0x52 / 255, 0x76 / 255)
    grey_rgb = (0x52 / 255, 0x60 / 255, 0x6D / 255)
    mm = 72.0 / 25.4

    starts = {front_pages + e["start_page"] - 1: e for e in entries}
    label_for: dict[int, str] = {}
    current = None
    for i in range(front_pages, doc.page_count):
        if i in starts:
            current = section_label(starts[i])
        if current:
            label_for[i] = current

    # Right half of the running head: the last h2 at or before each page
    # (every h2, including Sources, which is what such a page shows).
    heads = section_headings(dist)
    section_for: dict[int, str] = {}
    for e in entries:
        first = front_pages + e["start_page"] - 1
        last = first + e["pages"] - 1
        found = sorted((pg, text) for _id, text in heads.get(e["slug"], [])
                       if (pg := _page_for_heading(doc, text, first, last)) is not None)
        for i, (pg, text) in enumerate(found):
            end = found[i + 1][0] - 1 if i + 1 < len(found) else last
            for p in range(pg, end + 1):
                section_for[p] = text

    for i in range(cover_pages + 1, front_pages):
        page = doc[i]
        stamp_text(page, (12 * mm, 8 * mm), "Contents (continued)", 8, grey_rgb)
        page.draw_line(fitz.Point(12 * mm, 10 * mm), fitz.Point(136 * mm, 10 * mm), color=accent_rgb, width=0.3)

    # Contents rows jump to their target. Attached after the merge, because a
    # row's destination depends on how long the Contents itself runs. The whole
    # row is the click target, not just the digits.
    targets = contents_targets(entries, subs)
    linked, unlinked = 0, []
    for search_text, body_page in targets:
        target = link_target_page(front_pages, body_page)
        if not 0 <= target < doc.page_count:
            raise SystemExit(f"contents link for {search_text!r} would point at page {target + 1} "
                             f"of {doc.page_count}; page arithmetic is wrong")
        for i in range(cover_pages, front_pages):
            hits = doc[i].search_for(search_text)
            if hits:
                row = hits[0]
                doc[i].insert_link({"kind": fitz.LINK_GOTO,
                                    "from": fitz.Rect(12 * mm, row.y0 - 1, 136 * mm, row.y1 + 1),
                                    "page": target, "to": fitz.Point(0, 0)})
                linked += 1
                break
        else:
            unlinked.append(search_text)
    if linked != len(targets):
        raise SystemExit(f"linked {linked} of {len(targets)} contents rows; not found: "
                         + "; ".join(map(repr, unlinked[:5])))

    body_total = doc.page_count - front_pages
    for i in range(front_pages, doc.page_count):
        page = doc[i]
        if i not in starts and i in label_for:
            left = label_for[i]
            stamp_text(page, (12 * mm, 8 * mm), left, 8, grey_rgb)
            right = fit_running_head(left, section_for.get(i, ""), 124 * mm, 6 * mm, RUNHEAD_FONT, 8)
            if right:
                w = RUNHEAD_FONT.text_length(right, fontsize=8)
                stamp_text(page, (136 * mm - w, 8 * mm), right, 8, grey_rgb)
            page.draw_line(fitz.Point(12 * mm, 10 * mm), fitz.Point(136 * mm, 10 * mm), color=accent_rgb, width=0.3)
        num = f"{i - front_pages + 1} / {body_total}"
        nw = RUNHEAD_FONT.text_length(num, fontsize=8)
        stamp_text(page, (page.rect.width / 2 - nw / 2, page.rect.height - 22), num, 8, accent_rgb)

    anchors = build_anchor_map(dist)
    if not anchors:
        raise SystemExit(f"no heading anchors found in {dist}; is the build stale or empty?")
    stats = resolve_links(doc, entries, anchors, front_pages)
    print(format_link_summary(stats))
    if stats.unresolved_slug:
        raise SystemExit(f"{stats.unresolved_slug} internal link(s) point at a page that is not in this "
                         "build. A cross-reference is broken, or a subset render was assembled; render "
                         "the pages the links point at.")
    expected = expected_internal_targets(dist, [e["slug"] for e in entries])
    lost = expected - stats.internal_targets
    if lost:
        raise SystemExit(f"{len(lost)} cross-reference target(s) in the web pages have no jump in the PDF: "
                         + "; ".join(f"{s}#{f}" for s, f in sorted(lost)[:5]))
    print(f"Cross-references: all {len(expected)} distinct target(s) in the text resolved to a page.")

    doc.set_toc(toc_marks)
    doc.set_metadata({"title": BOOK_TITLE, "author": AUTHOR, "subject": BOOK_SUBJECT,
                      "keywords": "X-ray reflectivity; XRR; fitting; X-Ray Calc; multilayers; CC BY 4.0"})
    doc.save(str(DIST_FINAL), deflate=True, garbage=3)
    doc.close()
    print(f"\nFinal: {DIST_FINAL}  ({page_count(DIST_FINAL)} pages, {len(entries)} sections)")


if __name__ == "__main__":
    main()
