// Typesets the two formulas that float behind the cover's curve, with the
// book's own KaTeX and macros, so they read exactly as the chapters print them:
//   the Bragg law with refraction (NOTATION.md, Chapter 6), and
//   Parratt's recursion (Chapter 8, "Going Deeper").
// Change a formula in its chapter first, then here.
//
// Run by cover_hero.py (or: node pdf-build/cover-math.mjs)
// Out: pdf-build/cover-math.html, a fragment cover_html() in assemble.py inlines.

import katex from 'katex';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { KATEX_MACROS } from '../src/lib/katex-macros.mjs';

const FORMULAS = {
  bragg: String.raw`\sin^2\theta_m = \left(\frac{m\lambda}{2D}\right)^2 + 2\dbar`,
  parratt: String.raw`r_j = \frac{F_j + r_{j+1}\,e^{2i k_{j+1} H_{j+1}}}{1 + F_j\,r_{j+1}\,e^{2i k_{j+1} H_{j+1}}}`,
};

const html = Object.entries(FORMULAS)
  .map(([name, tex]) => `<div class="ghost ghost-${name}">${katex.renderToString(tex, {
    displayMode: true, macros: { ...KATEX_MACROS }, throwOnError: true, strict: true, output: 'html',
  })}</div>`)
  .join('\n');

const out = fileURLToPath(new URL('./cover-math.html', import.meta.url));
writeFileSync(out, `<!-- Generated by pdf-build/cover-math.mjs. Edit the script, not this file. -->\n${html}\n`);
console.log(`wrote ${out}`);
