"""Draw the cover's hero art: a measured multilayer curve and its fit.

The curve is the CoC4 fit of Chapter 18 (Polynomial order 1, chi2 0.96): the
measured points and the engine's calculated curve, both as stored in
figures-src/ch18/coc4-poly1-curves.dat. Nothing is recomputed here; this only
maps the stored (theta, R) pairs onto the hero's frame.

The frame follows the Vacuum book's cover rules: the hero is a cropped fragment
(the total-reflection plateau runs off the top-left, the eighth order is cut
by the bottom-right corner, the count floor falls off the bottom), and it is
monochrome except for the accent and the data. Its one text is a handwritten
note: the book's light touch, from the
subject itself rather than a mascot (author, 2026-09-25).

Run:  python pdf-build/cover_hero.py
Out:  pdf-build/cover-hero.svg, inlined by cover_html() in assemble.py, and
      (through cover-math.mjs) pdf-build/cover-math.html, the formulas behind it
"""
import math
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "figures-src" / "ch18" / "coc4-poly1-curves.dat"
OUT = HERE / "cover-hero.svg"

# viewBox units are 0.1 mm: 1480 x 1200 is the 148 x 120 mm hero area.
W, H = 1480, 1200
TT_MIN, TT_MAX = 0.50, 10.0        # 2θ (°) across the width
LOG_TOP, LOG_BOTTOM = 0.02, -5.0   # log10 R down the height; the count floor sits below


def read_sections(path: Path) -> dict[str, list[tuple[float, float]]]:
    out: dict[str, list[tuple[float, float]]] = {}
    cur = None
    for ln in path.read_text(encoding="utf-8").splitlines():
        if ln.startswith("# section"):
            cur = ln.split()[2]
            out[cur] = []
            continue
        if not ln or ln.startswith("#") or ln.startswith("theta"):
            continue
        t, r = (float(x) for x in ln.split()[:2])
        if r > 0:
            out[cur].append((t, r))
    return out


def xy(theta: float, r: float) -> tuple[float, float]:
    x = (2 * theta - TT_MIN) / (TT_MAX - TT_MIN) * W
    y = (LOG_TOP - math.log10(r)) / (LOG_TOP - LOG_BOTTOM) * H
    return x, y


def in_frame(x: float, y: float, pad: float = 40) -> bool:
    return -pad <= x <= W + pad and -pad <= y <= H + pad


def line_path(pts) -> str:
    """The fit as one polyline, broken where it leaves the frame."""
    parts, pen = [], False
    for t, r in pts:
        x, y = xy(t, r)
        if in_frame(x, y):
            parts.append(f"{'L' if pen else 'M'}{x:.1f} {y:.1f}")
            pen = True
        else:
            pen = False
    return "".join(parts)


def dot_path(pts) -> str:
    """The measured points as zero-length segments: with a round cap and the
    stroke width as the diameter, each draws a dot. One path instead of
    thousands of <circle> elements."""
    return "".join(f"M{x:.1f} {y:.1f}h0" for x, y in (xy(t, r) for t, r in pts) if in_frame(x, y, 0))


def grid() -> str:
    """Decade lines and every 2° of 2θ, far tier: chart paper, not axes."""
    rows = [f"M0 {xy(0, 10.0 ** k)[1]:.1f}H{W}" for k in range(0, -6, -1)]
    cols = [f"M{xy(tt / 2, 1)[0]:.1f} 0V{H}" for tt in range(2, 11, 2)]
    return "".join(rows + cols)


NOTE = ("make the line", "hit the dots!")
NOTE_AT = (700, 215)       # the first line's baseline start, in the empty sky right of order 1
NOTE_SIZE = 104            # units of 0.1 mm: about 29 pt


def note() -> str:
    """The handwritten note, floating in the empty sky right of order 1. It had
    arrows to the first four Bragg peaks; the author dropped them (2026-09-25)."""
    x0, y0 = NOTE_AT
    lines = "".join(
        f'<tspan x="{x0 + 30 * i}" y="{y0 + 1.1 * NOTE_SIZE * i:.0f}">{txt}</tspan>'
        for i, txt in enumerate(NOTE))
    return f"""<text font-family="'Ink Free','Segoe Print','Comic Sans MS',cursive" font-size="{NOTE_SIZE}"
        fill="#f2f4f5" opacity=".94" transform="rotate(-4 {x0} {y0})">{lines}</text>"""


def main() -> None:
    s = read_sections(SRC)
    svg = f"""<svg class="hero" viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg">
  <!-- Generated by pdf-build/cover_hero.py from figures-src/ch18/coc4-poly1-curves.dat.
       Edit the script, not this file. {{accent}}, {{tint}} and {{data}} are filled by cover_html(). -->
  <defs>
    <filter id="glow" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="7"/>
    </filter>
    <radialGradient id="vign" cx=".45" cy=".4" r=".75">
      <stop offset=".5" stop-color="#000" stop-opacity="0"/>
      <stop offset="1" stop-color="#000" stop-opacity=".5"/>
    </radialGradient>
    <linearGradient id="topfade" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#08090b" stop-opacity=".9"/>
      <stop offset="1" stop-color="#08090b" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="botfade" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#08090b" stop-opacity="0"/>
      <stop offset="1" stop-color="#08090b" stop-opacity=".85"/>
    </linearGradient>
  </defs>
  <!-- far tier: chart paper -->
  <path d="{grid()}" fill="none" stroke="#6e7681" stroke-width="1.2" opacity=".22"/>
  <!-- the fit: a blurred accent copy beneath the tint stroke -->
  <path d="{line_path(s['calc'])}" fill="none" stroke="{{accent}}" stroke-width="10"
        stroke-linejoin="round" opacity=".55" filter="url(#glow)"/>
  <path d="{line_path(s['calc'])}" fill="none" stroke="{{tint}}" stroke-width="2.6"
        stroke-linejoin="round"/>
  <!-- measured points on top of the fit, so both read -->
  <path d="{dot_path(s['measured'])}" fill="none" stroke="{{data}}" stroke-width="6"
        stroke-linecap="round" opacity=".8"/>
  <rect width="{W}" height="{H}" fill="url(#vign)"/>
  <rect width="{W}" height="40" fill="url(#topfade)"/>
  <!-- darkens the cropped bottom edge, where the copyright line sits -->
  <rect y="{H - 170}" width="{W}" height="170" fill="url(#botfade)"/>
  <!-- the handwritten note, above the vignette so it stays bright -->
  {note()}
</svg>
"""
    OUT.write_text(svg, encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")
    subprocess.run(["node", str(HERE / "cover-math.mjs")], check=True, cwd=HERE.parent)


if __name__ == "__main__":
    main()
